server:
  port: 5555
  servlet:
    context-path: /auth

spring:
  application:
    name: micro-auth-provider

  redis:
    database: 0
    host: 121.43.37.234
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

micro:
  auth:
    accessTokenValiditySeconds: 86400
    refreshTokenValiditySeconds: 604800
    clients:
      - client: qgh
        secret: 123456
        grantType: password,authorization_code,refresh_token
        scope: all